"""add name to locales

Revision ID: 1d586c14c767
Revises: 6802e60a78c3
Create Date: 2021-02-22 22:36:15.014074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d586c14c767'
down_revision = '6802e60a78c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locales', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locales', 'name')
    # ### end Alembic commands ###
