"""add locked to lock table

Revision ID: 37dc2f77f386
Revises: bc153baeef97
Create Date: 2021-02-23 21:46:12.928240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37dc2f77f386'
down_revision = 'bc153baeef97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locks', sa.Column('initiatorLocked', sa.Boolean(), nullable=False))
    op.add_column('locks', sa.Column('joinerLocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locks', 'joinerLocked')
    op.drop_column('locks', 'initiatorLocked')
    # ### end Alembic commands ###
