"""empty message

Revision ID: 3af17d1fa98f
Revises: 
Create Date: 2021-02-05 11:31:29.940123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af17d1fa98f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdWhen', sa.DateTime(), nullable=False),
    sa.Column('updatedWhen', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('phoneNumber', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phoneNumber'),
    sa.UniqueConstraint('username')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdWhen', sa.DateTime(), nullable=False),
    sa.Column('updatedWhen', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('endedWhen', sa.DateTime(), nullable=True),
    sa.Column('initiatorCompassDirection', sa.Numeric(), nullable=False),
    sa.Column('initiatorGPSLatitude', sa.Numeric(), nullable=False),
    sa.Column('initiatorGPSLongitude', sa.Numeric(), nullable=False),
    sa.Column('initiatorUserId', sa.Integer(), nullable=False),
    sa.Column('joinerCompassDirection', sa.Numeric(), nullable=True),
    sa.Column('joinerGPSLatitude', sa.Numeric(), nullable=True),
    sa.Column('joinerGPSLongitude', sa.Numeric(), nullable=True),
    sa.Column('joinerUserId', sa.Integer(), nullable=True),
    sa.Column('midwayGPSLatitude', sa.Numeric(), nullable=True),
    sa.Column('midwayGPSLongitude', sa.Numeric(), nullable=True),
    sa.Column('midwayPointCity', sa.String(length=100), nullable=True),
    sa.Column('startedWhen', sa.DateTime(), nullable=True),
    sa.Column('uniqueIdentifier', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['initiatorUserId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['joinerUserId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdWhen', sa.DateTime(), nullable=True),
    sa.Column('updatedWhen', sa.DateTime(), nullable=True),
    sa.Column('localTimezone', sa.DateTime(), nullable=True),
    sa.Column('GPSLatitude', sa.String(length=100), nullable=True),
    sa.Column('GPSLongitude', sa.String(length=100), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('temperatureFahrenheit', sa.Integer(), nullable=True),
    sa.Column('temperatureFeelsLikeFahrenheit', sa.Integer(), nullable=True),
    sa.Column('weatherDescription', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('conversations')
    op.drop_table('users')
    # ### end Alembic commands ###
