"""empty message

Revision ID: 53c585ec65d7
Revises: 3af17d1fa98f
Create Date: 2021-02-05 12:33:58.578900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53c585ec65d7'
down_revision = '3af17d1fa98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('localTimezoneOffset', sa.Integer(), nullable=True))
    op.drop_column('sessions', 'localTimezone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('localTimezone', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'localTimezoneOffset')
    # ### end Alembic commands ###
