"""empty message

Revision ID: 6802e60a78c3
Revises: cdc30b34b1e8
Create Date: 2021-02-22 22:29:10.975903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6802e60a78c3'
down_revision = 'cdc30b34b1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdWhen', sa.DateTime(), nullable=True),
    sa.Column('GPSLatitude', sa.String(length=100), nullable=True),
    sa.Column('GPSLongitude', sa.String(length=100), nullable=True),
    sa.Column('localTimezoneOffset', sa.Integer(), nullable=True),
    sa.Column('temperatureFahrenheit', sa.Integer(), nullable=True),
    sa.Column('temperatureFeelsLikeFahrenheit', sa.Integer(), nullable=True),
    sa.Column('updatedWhen', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('weatherDescription', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdWhen', sa.DateTime(), nullable=False),
    sa.Column('updatedWhen', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('endedWhen', sa.DateTime(), nullable=True),
    sa.Column('initiatorCompassDirection', sa.Numeric(), nullable=False),
    sa.Column('initiatorGPSLatitude', sa.Numeric(), nullable=False),
    sa.Column('initiatorGPSLongitude', sa.Numeric(), nullable=False),
    sa.Column('initiatorUserId', sa.Integer(), nullable=False),
    sa.Column('joinerCompassDirection', sa.Numeric(), nullable=True),
    sa.Column('joinerGPSLatitude', sa.Numeric(), nullable=True),
    sa.Column('joinerGPSLongitude', sa.Numeric(), nullable=True),
    sa.Column('joinerUserId', sa.Integer(), nullable=True),
    sa.Column('midwayGPSLatitude', sa.Numeric(), nullable=True),
    sa.Column('midwayGPSLongitude', sa.Numeric(), nullable=True),
    sa.Column('midwayPointCity', sa.String(length=100), nullable=True),
    sa.Column('startedWhen', sa.DateTime(), nullable=True),
    sa.Column('uniqueIdentifier', sa.Numeric(precision=40, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['initiatorUserId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['joinerUserId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('talks')
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('createdWhen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedWhen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('GPSLatitude', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('GPSLongitude', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temperatureFahrenheit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temperatureFeelsLikeFahrenheit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weatherDescription', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('localTimezoneOffset', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='sessions_userId_fkey'),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey')
    )
    op.create_table('talks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('createdWhen', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updatedWhen', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('endedWhen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('initiatorCompassDirection', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('initiatorGPSLatitude', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('initiatorGPSLongitude', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('initiatorUserId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joinerCompassDirection', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('joinerGPSLatitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('joinerGPSLongitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('joinerUserId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('midwayGPSLatitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('midwayGPSLongitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('midwayPointCity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('startedWhen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uniqueIdentifier', sa.NUMERIC(precision=40, scale=0), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['initiatorUserId'], ['users.id'], name='talks_initiatorUserId_fkey'),
    sa.ForeignKeyConstraint(['joinerUserId'], ['users.id'], name='talks_joinerUserId_fkey'),
    sa.PrimaryKeyConstraint('id', name='talks_pkey')
    )
    op.drop_table('locks')
    op.drop_table('locales')
    # ### end Alembic commands ###
