"""initial migration

Revision ID: 7c92f93c33e6
Revises: 
Create Date: 2021-03-19 12:12:21.271174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c92f93c33e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdWhen', sa.DateTime(), nullable=False),
    sa.Column('updatedWhen', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('phoneNumber', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phoneNumber'),
    sa.UniqueConstraint('username')
    )
    op.create_table('locales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdWhen', sa.DateTime(), nullable=True),
    sa.Column('GPSLatitude', sa.String(length=100), nullable=True),
    sa.Column('GPSLongitude', sa.String(length=100), nullable=True),
    sa.Column('localTimezoneOffset', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('sunrise', sa.String(length=100), nullable=True),
    sa.Column('sunset', sa.String(length=100), nullable=True),
    sa.Column('temperatureFahrenheit', sa.Integer(), nullable=True),
    sa.Column('temperatureFeelsLikeFahrenheit', sa.Integer(), nullable=True),
    sa.Column('updatedWhen', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('weatherDescription', sa.String(length=50), nullable=True),
    sa.Column('weatherDescriptionDetailed', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdWhen', sa.DateTime(), nullable=False),
    sa.Column('updatedWhen', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('endedWhen', sa.DateTime(), nullable=True),
    sa.Column('initiatorCompassDirection', sa.Numeric(), nullable=False),
    sa.Column('initiatorGPSLatitude', sa.Numeric(), nullable=False),
    sa.Column('initiatorGPSLongitude', sa.Numeric(), nullable=False),
    sa.Column('initiatorLocked', sa.Boolean(), nullable=True),
    sa.Column('initiatorUserId', sa.Integer(), nullable=False),
    sa.Column('joinerCompassDirection', sa.Numeric(), nullable=True),
    sa.Column('joinerGPSLatitude', sa.Numeric(), nullable=True),
    sa.Column('joinerGPSLongitude', sa.Numeric(), nullable=True),
    sa.Column('joinerLocked', sa.Boolean(), nullable=True),
    sa.Column('joinerUserId', sa.Integer(), nullable=True),
    sa.Column('midwayGPSLatitude', sa.Numeric(), nullable=True),
    sa.Column('midwayGPSLongitude', sa.Numeric(), nullable=True),
    sa.Column('midwayPointCity', sa.String(length=100), nullable=True),
    sa.Column('startedWhen', sa.DateTime(), nullable=True),
    sa.Column('uniqueIdentifier', sa.Numeric(precision=40, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['initiatorUserId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['joinerUserId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locks')
    op.drop_table('locales')
    op.drop_table('users')
    # ### end Alembic commands ###
