"""update user table

Revision ID: 8f34181071d0
Revises: b4bbc66a7a11
Create Date: 2021-02-26 11:57:37.736197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f34181071d0'
down_revision = 'b4bbc66a7a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firstName',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'lastName',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'phoneNumber',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phoneNumber',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'lastName',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'firstName',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
