"""add detailed weather description and sunrise & sunset to locale table

Revision ID: bc153baeef97
Revises: 1d586c14c767
Create Date: 2021-02-22 23:43:32.567727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc153baeef97'
down_revision = '1d586c14c767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locales', sa.Column('sunrise', sa.String(length=100), nullable=True))
    op.add_column('locales', sa.Column('sunset', sa.String(length=100), nullable=True))
    op.add_column('locales', sa.Column('weatherDescriptionDetailed', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locales', 'weatherDescriptionDetailed')
    op.drop_column('locales', 'sunset')
    op.drop_column('locales', 'sunrise')
    # ### end Alembic commands ###
