"""empty message

Revision ID: cdc30b34b1e8
Revises: 53c585ec65d7
Create Date: 2021-02-06 20:01:10.748621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cdc30b34b1e8'
down_revision = '53c585ec65d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdWhen', sa.DateTime(), nullable=False),
    sa.Column('updatedWhen', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('endedWhen', sa.DateTime(), nullable=True),
    sa.Column('initiatorCompassDirection', sa.Numeric(), nullable=False),
    sa.Column('initiatorGPSLatitude', sa.Numeric(), nullable=False),
    sa.Column('initiatorGPSLongitude', sa.Numeric(), nullable=False),
    sa.Column('initiatorUserId', sa.Integer(), nullable=False),
    sa.Column('joinerCompassDirection', sa.Numeric(), nullable=True),
    sa.Column('joinerGPSLatitude', sa.Numeric(), nullable=True),
    sa.Column('joinerGPSLongitude', sa.Numeric(), nullable=True),
    sa.Column('joinerUserId', sa.Integer(), nullable=True),
    sa.Column('midwayGPSLatitude', sa.Numeric(), nullable=True),
    sa.Column('midwayGPSLongitude', sa.Numeric(), nullable=True),
    sa.Column('midwayPointCity', sa.String(length=100), nullable=True),
    sa.Column('startedWhen', sa.DateTime(), nullable=True),
    sa.Column('uniqueIdentifier', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['initiatorUserId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['joinerUserId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('conversations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('createdWhen', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updatedWhen', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('endedWhen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('initiatorCompassDirection', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('initiatorGPSLatitude', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('initiatorGPSLongitude', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('initiatorUserId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joinerCompassDirection', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('joinerGPSLatitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('joinerGPSLongitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('joinerUserId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('midwayGPSLatitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('midwayGPSLongitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('midwayPointCity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('startedWhen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uniqueIdentifier', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['initiatorUserId'], ['users.id'], name='conversations_initiatorUserId_fkey'),
    sa.ForeignKeyConstraint(['joinerUserId'], ['users.id'], name='conversations_joinerUserId_fkey'),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey')
    )
    op.drop_table('talks')
    # ### end Alembic commands ###
