"""initial migration

Revision ID: e5d1c27c2e03
Revises: 
Create Date: 2021-02-03 19:50:15.693687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d1c27c2e03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phoneNumber', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('lastUpdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phoneNumber'),
    sa.UniqueConstraint('username')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniqueIdentifier', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('initiatorUserId', sa.Integer(), nullable=False),
    sa.Column('joinerUserId', sa.Integer(), nullable=True),
    sa.Column('initiatorGPSLocation', sa.String(length=100), nullable=False),
    sa.Column('joinerGPSLocation', sa.String(length=100), nullable=True),
    sa.Column('initiatorDirection', sa.String(length=100), nullable=False),
    sa.Column('joinerDirection', sa.String(length=100), nullable=True),
    sa.Column('midwayGPSLocation', sa.String(length=100), nullable=True),
    sa.Column('midwayCity', sa.String(length=50), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['initiatorUserId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['joinerUserId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('GPSLocation', sa.String(length=100), nullable=True),
    sa.Column('weather', sa.String(length=255), nullable=True),
    sa.Column('localTime', sa.DateTime(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('conversations')
    op.drop_table('users')
    # ### end Alembic commands ###
